# Generated by Django 5.2.17 on 2026-09-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="emails_emai_tenant__0f718b_idx",
            old_name="emaillog_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="emails_emai_to_emai_021ad4_idx",
            old_name="emaillog_toemail_created_idx",
        ),
        migrations.RenameIndex(
            model_name="emaillog",
            new_name="emails_emai_status_e97e19_idx",
            old_name="emaillog_status_idx",
        ),
    ]
