# Generated by Django 5.2.17 on 2026-10-04 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0004_member_baptism_date_member_is_baptized"),
        ("tenants", "0006_alter_tenant_country_alter_tenant_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("meeting", "Meeting"),
                            ("retreat", "Retreat"),
                            ("conference", "Conference"),
                            ("camp", "Camp"),
                            ("special", "Special activity"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "events",
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("registered", "Registered"), ("cancelled", "Cancelled")],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="events.event"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Registration",
                "verbose_name_plural": "Event Registrations",
                "db_table": "event_registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["tenant", "start_at"], name="events_tenant__bdbfd1_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["tenant", "is_active"], name="events_tenant__1b198b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together={("member", "event")},
        ),
    ]
