# Generated by Django 5.2.17 on 2026-10-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="required_courses",
            field=models.ManyToManyField(blank=True, related_name="required_for_events", to="education.course"),
        ),
        migrations.AddField(
            model_name="event",
            name="requires_baptized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="requires_married",
            field=models.BooleanField(default=False),
        ),
    ]
