# Generated by Django 5.2.17 on 2026-10-04 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_required_courses_event_requires_baptized_and_more"),
        ("members", "0004_member_baptism_date_member_is_baptized"),
        ("tenants", "0006_alter_tenant_country_alter_tenant_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="events.event"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Attendance",
                "verbose_name_plural": "Event Attendances",
                "db_table": "event_attendances",
                "ordering": ["-checked_in_at"],
                "indexes": [models.Index(fields=["tenant", "event"], name="event_atten_tenant__c30f28_idx")],
                "unique_together": {("member", "event")},
            },
        ),
    ]
