# Generated by Django 5.2.17 on 2026-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('service', 'Servicio'), ('meeting', 'Reunión'), ('retreat', 'Retiro'), ('conference', 'Conferencia'), ('camp', 'Campamento'), ('special', 'Actividad especial'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'Inscrito'), ('cancelled', 'Cancelado')], default='registered', max_length=20),
        ),
    ]
