# Generated by Django 5.2.17 on 2026-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.CharField(choices=[('tithe', 'Diezmo'), ('offering', 'Ofrenda general'), ('building', 'Fondo de construcción'), ('missions', 'Misiones'), ('youth', 'Jóvenes'), ('other', 'Otro')], default='offering', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('one_time', 'Única vez'), ('recurring', 'Recurrente')], default='one_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('operations', 'Operaciones'), ('salaries', 'Salarios'), ('utilities', 'Servicios'), ('maintenance', 'Mantenimiento'), ('programs', 'Programas'), ('missions', 'Misiones'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('paid', 'Pagado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
