# Generated by Django 5.2.12 on 2026-03-29 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Church Name')),
                ('slug', models.SlugField(blank=True, max_length=63, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain for this church (e.g., "miiglesia" for miiglesia.sgchurch.app)', max_length=63, unique=True)),
                ('denomination', models.CharField(blank=True, choices=[('catholic', 'Catholic'), ('baptist', 'Baptist'), ('methodist', 'Methodist'), ('presbyterian', 'Presbyterian'), ('lutheran', 'Lutheran'), ('anglican', 'Anglican'), ('evangelical', 'Evangelical'), ('pentecostal', 'Pentecostal'), ('charismatic', 'Charismatic'), ('nondenominational', 'Non-denominational'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='church_logos/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=64)),
                ('stripe_onboarding_complete', models.BooleanField(default=False)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('MXN', 'Mexican Peso'), ('COP', 'Colombian Peso'), ('ARS', 'Argentine Peso'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('enable_families', models.BooleanField(default=True)),
                ('enable_tags', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
                'db_table': 'tenant_domains',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
    ]
