# Generated by Django 5.2.12 on 2026-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
