# Generated by Django 5.2.12 on 2026-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_country_alter_tenant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
