# Generated by Django 5.2.17 on 2026-10-01 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0004_member_baptism_date_member_is_baptized"),
        ("tenants", "0006_alter_tenant_country_alter_tenant_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseBlock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="course_blocks", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Block",
                "verbose_name_plural": "Course Blocks",
                "db_table": "course_blocks",
                "ordering": ["name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("requires_baptized", models.BooleanField(default=False)),
                ("requires_married", models.BooleanField(default=False)),
                (
                    "order_in_block",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Display order within the block (ignored for independent courses)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prerequisite_courses",
                    models.ManyToManyField(blank=True, related_name="unlocks_courses", to="education.course"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="courses", to="tenants.tenant"
                    ),
                ),
                (
                    "course_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="education.courseblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["course_block__name", "order_in_block", "title"],
            },
        ),
        migrations.CreateModel(
            name="BlockCertificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_number", models.CharField(editable=False, max_length=40, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_certificates",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_certificates",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "course_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="education.courseblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Block Certificate",
                "verbose_name_plural": "Block Certificates",
                "db_table": "block_certificates",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("enrolled", "Enrolled"), ("completed", "Completed"), ("dropped", "Dropped")],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="education.course"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="members.member"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["tenant", "is_active"], name="courses_tenant__64e166_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["course_block"], name="courses_course__1e4115_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="blockcertificate",
            unique_together={("member", "course_block")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["tenant", "status"], name="enrollments_tenant__073ee7_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["member", "status"], name="enrollments_member__f5ba15_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("member", "course")},
        ),
    ]
