# Generated by Django 5.2.17 on 2026-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Inscrito'), ('completed', 'Completado'), ('dropped', 'Retirado')], default='enrolled', max_length=20),
        ),
    ]
