# Generated by Django 5.2.17 on 2026-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_member_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="is_baptized",
            field=models.BooleanField(default=False),
        ),
    ]
