# Generated by Django 5.2.17 on 2026-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_baptism_date_member_is_baptized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Soltero/a'), ('married', 'Casado/a'), ('divorced', 'Divorciado/a'), ('widowed', 'Viudo/a')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.CharField(choices=[('visitor', 'Visitante'), ('attendee', 'Asistente'), ('member', 'Miembro'), ('inactive', 'Inactivo')], default='visitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('pastor', 'Pastor'), ('treasurer', 'Tesorero/a'), ('teacher', 'Maestro/a'), ('volunteer', 'Voluntario/a'), ('member', 'Miembro')], default='member', max_length=20),
        ),
    ]
