# Generated by Django 5.2.17 on 2026-09-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_tenant__6ae88e_idx",
            old_name="notif_tenant_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_tenant__9a5521_idx",
            old_name="notif_tenant_read_created_idx",
        ),
    ]
